version: "3"
services:
    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto
        ports:
            - '1883:1883'
            - '9001:9001'
        volumes:
            - ./mosquitto/:/mosquitto/
        restart: always

    python-http-server:
        container_name: python-http-server
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        command: python -m http.server